version: "3.7"

services:
  mongo:
    image: mongo:latest
    container_name: ${database_name}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${admin_user}
      MONGO_INITDB_ROOT_PASSWORD: ${admin_password}
      MONGO_INITDB_DATABASE: ${database_name}
      DB_USERNAME: ${db_user}
      DB_PASSWORD: ${db_password}
      DB_PORT: ${db_port}
    volumes:
      - ./database:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${db_port}:27017
